# .github/ISSUE_TEMPLATE/documentation.yml
---
name: Documentation
description: Report an issue with documentation or suggest improvements
title: "[DOCS]: "
labels: ["documentation"]
assignees: "anal87"

---

**What is the documentation issue?**
A clear and concise description of what the documentation issue is.

**Where is the issue located?**
- [ ] README.md
- [ ] Wiki pages
- [ ] Code comments
- [ ] Other (please specify)

**Suggested improvement**
How would you like the documentation to be improved?

**Additional context**
Add any other context about the documentation issue here.
